name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install

      - uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: lint

      - uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: test

      - uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: build
