name: Deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Yarn cache
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-deploy-${{ env.cache-name }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install

      - name: Build
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
