name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Yarn cache
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-tests-${{ env.cache-name }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install

      - name: Check formatting and lint
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: lint

      - name: Run test suite
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: test
